// The one place that opens the database. Everything else imports `db` from here
// and calls db.query(sql, params) / db.exec(sql). Two drivers sit behind that
// uniform interface, chosen by the DATABASE_URL scheme:
//
//   - sqlite (default in dev): bun:sqlite, zero external infrastructure.
//   - postgres (prod): Bun's native Bun.SQL, no third-party driver.
//
// Queries are written once with `?` positional placeholders (SQLite's native
// form); the Postgres driver rewrites them to $1, $2, ... The schema is
// dialect-neutral (see schema.sql), so the same SQL runs on both. Timestamps and
// ids are TEXT and generated by the app, which keeps the two engines byte-for-
// byte comparable (important for the optimistic-concurrency check).

import { SQL } from 'bun';
import { Database } from 'bun:sqlite';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { config } from './config';

export type DbKind = 'postgres' | 'sqlite';

export interface Driver {
  query(sql: string, params?: unknown[]): Promise<any[]>;
  exec(sql: string): Promise<void> | void;
}

const here = dirname(fileURLToPath(import.meta.url));

function isPostgres(url: string) {
  return /^postgres(ql)?:\/\//i.test(url);
}

function makePostgres(url: string): Driver {
  const sql = new SQL(url);
  return {
    async query(text, params = []) {
      let i = 0;
      const pg = text.replace(/\?/g, () => `$${++i}`);
      return params.length ? sql.unsafe(pg, params) : sql.unsafe(pg);
    },
    async exec(text) {
      // Bun.SQL sends one statement per query; split the (comment-stripped) file.
      const cleaned = text.split('\n').filter((l) => !l.trim().startsWith('--')).join('\n');
      for (const stmt of cleaned.split(';').map((s) => s.trim()).filter(Boolean)) {
        await sql.unsafe(stmt);
      }
    },
  };
}

function sqlitePath(url: string): string {
  const p = url.replace(/^sqlite:\/\//i, '').replace(/^file:/i, '');
  return p === '' || p === ':memory:' ? ':memory:' : p;
}

function makeSqlite(url: string): Driver {
  const sqlite = new Database(sqlitePath(url), { create: true });
  sqlite.exec('PRAGMA journal_mode = WAL;');
  sqlite.exec('PRAGMA foreign_keys = ON;');
  return {
    async query(sql, params = []) {
      const stmt = sqlite.query(sql);
      if (/^\s*select/i.test(sql)) return stmt.all(...(params as any[]));
      stmt.run(...(params as any[]));
      return [];
    },
    exec(sql) {
      sqlite.exec(sql); // bun:sqlite runs multiple statements and -- comments
    },
  };
}

export const dbKind: DbKind = isPostgres(config.databaseUrl) ? 'postgres' : 'sqlite';
export const db: Driver = dbKind === 'postgres'
  ? makePostgres(config.databaseUrl)
  : makeSqlite(config.databaseUrl);

// ISO timestamp used for created_at/updated_at so the value the client sees is
// exactly what optimistic-concurrency comparisons run against.
export const now = () => new Date().toISOString();

// Applies schema.sql. It is all CREATE ... IF NOT EXISTS, so it is safe on every
// boot, on either engine.
export async function migrate() {
  const text = readFileSync(join(here, 'schema.sql'), 'utf8');
  await db.exec(text);
}
